import type { Metadata } from 'next';
import React from 'react';
import { Space_Grotesk } from 'next/font/google';
import './styles/globals.css';
import './styles/tailwind.css';
import Header from './ui/header';
import Footer from './ui/footer';

const space = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${space.className} text-white relative`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
